import { Geist, Geist_Mono , Doto, Montserrat} from "next/font/google";
import "./globals.css";
import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";

export const doto = Doto({
  variable: "--font-doto",
  weight: ["400",],
  subsets: ["latin"],
  display: "swap",
});

export const monte = Montserrat({
  variable: "--font-monte",
  weight: ["400","700"],
  subsets: ["latin"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

// export const metadata = {
//   title: "interactive portfolio",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
